version: "3.4"

services:
  blackfire:
    image: blackfire/blackfire:latest
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    depends_on:
      - php

  elasticsearch:
    image: ajardin/magento2-elasticsearch:latest
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  maildev:
    image: djfarrelly/maildev:latest
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    depends_on:
      - php
    ports:
      - 1080:80

  mysql:
    image: ajardin/magento2-mysql:latest
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  nginx:
    image: ajardin/magento2-nginx:latest
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    ports:
      - 443:443
    volumes:
      # Project files
      - ${PROJECT_LOCATION}:/var/www/html:delegated
      # SSL certificates
      - ${PROJECT_LOCATION}/var/docker/nginx/certs:/etc/nginx/ssl:cached
      # Custom configuration
      - ${PROJECT_LOCATION}/var/docker/nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    depends_on:
      - php
    tty: true

  php:
    image: ajardin/magento2-php:${DOCKER_PHP_IMAGE}
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      # Project files
      - ${PROJECT_LOCATION}:/var/www/html:delegated
      # Custom configuration
      - ${PROJECT_LOCATION}/var/docker/php/php-cli.ini:/usr/local/etc/php/php-cli.ini:ro
      - ${PROJECT_LOCATION}/var/docker/php/php-fpm-fcgi.ini:/usr/local/etc/php/php-fpm-fcgi.ini:ro
      # SSH socket
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    tty: true

  redis:
    image: redis:3.2-alpine
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    volumes:
      - redis:/data
    tty: true

volumes:
  elasticsearch: {}
  mysql: {}
  redis: {}
