version: "3.7"

services:
  blackfire:
    image: blackfire/blackfire:latest
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    depends_on:
      - php

  elasticsearch:
    image: ajardin/magento2-elasticsearch:latest
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  database:
    image: mariadb:${DOCKER_DATABASE_IMAGE}
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    tty: true

  maildev:
    image: djfarrelly/maildev:latest
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    depends_on:
      - php
    ports:
      - 1080:80

  nginx:
    image: ajardin/magento2-nginx:latest
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    ports:
      - 443:443
    volumes:
      # Project files
      - code:/var/www/html:delegated
      # SSL certificates
      - ${PROJECT_LOCATION}/var/docker/nginx/certs:/etc/nginx/ssl:cached
      # Custom configuration
      - ${PROJECT_LOCATION}/var/docker/nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    depends_on:
      - php
    tty: true

  php:
    image: ajardin/magento2-php:${DOCKER_PHP_IMAGE}
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      # Project files
      - code:/var/www/html:delegated
      # Custom configuration
      - ${PROJECT_LOCATION}/var/docker/php/php-cli.ini:/usr/local/etc/php/php-cli.ini:ro
      - ${PROJECT_LOCATION}/var/docker/php/php-fpm-fcgi.ini:/usr/local/etc/php/php-fpm-fcgi.ini:ro
      # SSH socket
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    tty: true

  redis:
    image: redis:3.2-alpine
    env_file: ${PROJECT_LOCATION}/var/docker/.env
    volumes:
      - redis:/data
    tty: true

volumes:
  code: {}
  elasticsearch: {}
  database: {}
  redis: {}

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
      mode: two-way-resolved
      symlink:
        mode: posix-raw
      configurationBeta:
        permissions:
          defaultOwner: id:1000
          defaultGroup: id:1000
          defaultFileMode: 0644
          defaultDirectoryMode: 0755
    code:
      alpha: ${PROJECT_LOCATION}
      beta: "volume://code"
