name: CI

on:
  push:
    branches: ['**']

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Install system requirements'
        run: |
          sudo apt update
          sudo apt install -y libicu-dev
          sudo apt-fast install -y --no-install-recommends \
            php7.4 php7.4-intl php7.4-mbstring php7.4-pcov php7.4-sqlite php7.4-xml

      - name: 'Install Composer dependencies'
        run: composer install --optimize-autoloader --classmap-authoritative

      - name: 'Execute PHP-CS-Fixer in dry-run'
        run: make phpcsfixer-audit

      - name: 'Execute a copy/paste analysis'
        run: make phpcpd

      - name: 'Execute PHPStan analysis'
        run: make phpstan

      - name: 'Execute security analysis'
        run: make security

      - name: 'Execute PHPUnit tests and send report to Codecov'
        run: |
          make tests
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
