name: CI

on:
  push:
    branches: ['**']

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Install system requirements'
        run: |
          sudo mkdir -p /run/php/
          sudo apt-get update
          sudo apt-get install -y libicu-dev php-intl

      - name: 'Install Composer dependencies'
        run: composer install --optimize-autoloader --classmap-authoritative

      - name: 'Execute PHP-CS-Fixer in dry-run'
        run: make phpcsfixer-audit

      - name: 'Execute a copy/paste analysis'
        run: make phpcpd

      - name: 'Execute PHPStan analysis'
        run: make phpstan

      - name: 'Execute security analysis'
        run: make security

      - name: 'Execute PHPUnit tests and send report to Codecov'
        run: |
          ./bin/console doctrine:database:create --env=test
          ./bin/console doctrine:schema:create --env=test
          ./bin/console doctrine:fixtures:load --no-interaction --env=test
          ./bin/phpunit --testdox
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
