name: Continuous Integration

on:
  push:
    branches: ['**']

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: 'Install system requirements'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl, mbstring, xml
          coverage: pcov
        env:
          fail-fast: true

      - name: 'Install Composer dependencies'
        run: |
          composer validate --strict --ansi
          composer install --optimize-autoloader --classmap-authoritative --ansi

      - name: 'Execute PHP-CS-Fixer in dry-run'
        run: make phpcsfixer-audit

      - name: 'Execute a copy/paste analysis'
        run: make phpcpd

      - name: 'Execute Psalm analysis'
        run: make psalm

      - name: 'Execute security analysis'
        run: make security

      - name: 'Execute PHPUnit tests and send report to Codecov'
        run: |
          ./bin/phpunit --testdox
          bash <(curl -s https://codecov.io/bash) -Z
